# -*- coding: utf-8 -*-
"""Análisis ORC.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rBuXg0CPHg_EgYIexdbnro07xYTlRdLf
"""

from google.colab import drive

   drive.mount('/content/drive')

# Diagnóstico
with open('NOMBRE DE ARCHIVOS', 'r') as f:
    for i, linea in enumerate(f):
        print(f"[{i}] {linea.strip()}")
        if i > 10:
            break

import pandas as pd

datos = pd.read_csv('NOMBRE DE ARCHIVOS', skiprows=14).dropna()
datos.head()

import pandas as pd
import matplotlib.pyplot as plt

datos = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/T0033ALL.CSV', skiprows=15, header=0, on_bad_lines='skip')

# nombres de columnas
datos.columns = datos.columns.str.strip()
print("Columnas detectadas:", datos.columns.tolist())

#Renombra
datos = datos.rename(columns={
    'Label': 'Tiempo',
    'TIME' : 'Tiempo',
    'CH1'  : 'CH1',
    'CH2'  : 'CH2',
    'CH3'  : 'CH3',
    'CH4'  : 'CH4',
})

# Eliminar la fila 0 que tiene los nombres como valores
datos = datos[datos['Tiempo'] != 'TIME'].reset_index(drop=True)

# Conversión a número
for col in datos.columns:
    datos[col] = pd.to_numeric(datos[col], errors='coerce')

datos = datos.dropna()

# Ajuste de tiempo
datos['Tiempo'] = datos['Tiempo'] - datos['Tiempo'].min()

print(datos.dtypes)
print(datos.head())


fig, ax = plt.subplots()

datos.plot(x='Tiempo', y='CH1', ax=ax, color='tab:purple')
datos.plot(x='Tiempo', y='CH2', ax=ax, color='tab:red')
datos.plot(x='Tiempo', y='CH3', ax=ax, color='tab:orange')
datos.plot(x='Tiempo', y='CH4', ax=ax, color='tab:green')

ax.set_xlabel("Tiempo (s)", fontdict={'fontsize': 14, 'fontweight': 'bold', 'color': 'tab:blue'})
ax.set_ylabel("Voltaje (V)")
ax.grid(axis='y', color='gray', linestyle='dashed')
ax.grid(axis='x', color='gray', linestyle='dashed')

plt.show()

